DROP DATABASE IF EXISTS vsa_pr2;
CREATE DATABASE vsa_pr2;
GRANT ALL PRIVILEGES ON DATABASE vsa_pr2 TO vsa;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vsa;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO vsa;
